export interface fooditem{
    id: string,
    allergens: string[],
    available: boolean,
    available_time : string[],
    calories : number,
    carbs: number,
    combo_items: string[],
    cooking_method : string,
    cuisine: string,
    description: string,
    diet: string,
    dish_type: string,
    fat: number,
    flavor_tags: string[],
    image_url: string,
    ingredients: string[],
    is_best_seller: boolean,
    meal_type: string[],
    name: string,
    occasion: string[],
    pairs_well_with: string[],
    portion_size: string,
    prep_time: string,
    price: number,
    protein: number,
    rating: number,
    review_count: number,
    serves: string,
    spice_level: string,
    taste_profile: string[]
}